### ISSUE TITLE
Doesn't work on Manjaro KDE, either the AUR or a plain uzipped version

### ISSUE THREAD

**Issue by quesada** [pavelfatin/typometer#11]

**Comment by quesada** [comment]
q@neo ~/D/typometer-1.0.1> java -jar typometer-1.0.1.jar &

(java:17133): Gtk-WARNING **: 15:05:34.400: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
java.lang.ExceptionInInitializerError
        at com.pavelfatin.typometer.ui.MainFrame.<init>(MainFrame.java:120)
        at com.pavelfatin.typometer.Application.openMainForm(Application.java:41)
        at com.pavelfatin.typometer.Application.lambda$main$0(Application.java:31)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field java.awt.Color java.awt.Component.background accessible: module java.desktop does not "opens java.awt" to unnamed module @2b831353
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:35q@neo ~/D/typometer-1.0.1> java -jar typometer-1.0.1.jar &
7)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at com.pavelfatin.typometer.ui.ColoredRenderer.createBackgroundField(ColoredRenderer.java:36)
        at com.pavelfatin.typometer.ui.ColoredRenderer.<clinit>(ColoredRenderer.java:28)
        ... 16 more

**Comment by SpicyRicecaker** [comment]
What version of java are you using? Even though the readme says "Java 8 or latter", for me both Java 16 and 11 didn't work and gave me an error very similar to yours. Had to downgrade to Java 8 to run it

**Comment by quesada** [comment]
Thanks will try that

**Comment by ringofyre** [comment]
I can confirm similar issue.

`java -jar typometer-1.0.1.jar 
java.lang.ExceptionInInitializerError
  at com.pavelfatin.typometer.ui.MainFrame.<init>(MainFrame.java:120)
  at com.pavelfatin.typometer.Application.openMainForm(Application.java:41)
  at com.pavelfatin.typometer.Application.lambda$main$0(Application.java:31)
  at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
  at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
  at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
  at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
  at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
  at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field java.awt.Color java.awt.Component.background accessible: module java.desktop does not "opens java.awt" to unnamed module @171b706d
  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
  at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
  at com.pavelfatin.typometer.ui.ColoredRenderer.createBackgroundField(ColoredRenderer.java:36)
  at com.pavelfatin.typometer.ui.ColoredRenderer.<clinit>(ColoredRenderer.java:28)
  ... 16 more`

& java ver. is

`java --version
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Debian-1, mixed mode, sharing)`

`uname -a
Linux ProBook440 6.7.10-x64v3-xanmod1 #0~20240315.g13c816f SMP PREEMPT_DYNAMIC Fri Mar 15 22:20:45 UTC x86_64 GNU/Linux
`

**Comment by HatefulMoron** [comment]
I can confirm that I experienced the same issue on a recent version of Java -- downgrading to openjdk version 9.181 worked for me.
